### Home page test
GET https://cst8919lab2app.azurewebsites.net/

### Successful login
POST https://cst8919lab2app.azurewebsites.net/login
Content-Type: application/json

{
  "username": "admin",
  "password": "Password123"
}

### Failed login 1
POST https://cst8919lab2app.azurewebsites.net/login
Content-Type: application/json

{
  "username": "admin",
  "password": "wrongpass"
}

### Failed login 2
POST https://cst8919lab2app.azurewebsites.net/login
Content-Type: application/json

{
  "username": "admin",
  "password": "wrongpass"
}
