### Home Page
GET https://cst8919-lab2-hycst.azurewebsites.net/

###

### Successful Login
POST https://cst8919-lab2-hycst.azurewebsites.net/login
Content-Type: application/json

{
    "username":"admin",
    "password":"Password123"
}

###

### Failed Login 1
POST https://cst8919-lab2-hycst.azurewebsites.net/login
Content-Type: application/json

{
    "username":"admin",
    "password":"wrongpassword"
}

###

### Failed Login 2
POST https://cst8919-lab2-hycst.azurewebsites.net/login
Content-Type: application/json

{
    "username":"user1",
    "password":"123456"
}

###

### Failed Login 3
POST https://cst8919-lab2-hycst.azurewebsites.net/login
Content-Type: application/json

{
    "username":"guest",
    "password":"abc"
}
